const renderedGeometryProperties: any = {
  Box: ['nodeId', 'treeIndex', 'color', 'center', 'normal', 'angle', 'delta'],
  Circle: ['nodeId', 'treeIndex', 'color', 'center', 'normal', 'radius'],
  Cone: ['nodeId', 'treeIndex', 'color', 'centerA', 'centerB', 'radiusA', 'radiusB', 'angle', 'arcAngle'],
  EccentricCone: ['nodeId', 'treeIndex', 'color', 'centerA', 'centerB', 'radiusA', 'radiusB', 'normal'],
  EllipsoidSegment: ['nodeId', 'treeIndex', 'color', 'center', 'normal', 'horizontalRadius', 'verticalRadius',
    'height'],
  GeneralCylinder: ['nodeId', 'treeIndex', 'color', 'centerA', 'centerB', 'radius', 'heightA', 'heightB', 'slopeA',
    'slopeB', 'zAngleA', 'zAngleB', 'angle', 'arcAngle'],
  GeneralRing: ['nodeId', 'treeIndex', 'color', 'center', 'normal', 'localXAxis', 'xRadius', 'yRadius', 'thickness',
    'angle', 'arcAngle'],
  InstancedMesh: ['nodeId', 'treeIndex', 'color', 'transformMatrix?'],
  MergedMesh: ['triangleOffset', 'triangleCount', 'nodeId', 'treeIndex', 'color', 'transformMatrix?'],
  Nut: ['nodeId', 'treeIndex', 'color', 'centerA', 'centerB', 'radius', 'rotationAngle'],
  Quad: ['nodeId', 'treeIndex', 'color', 'vertex1', 'vertex2', 'vertex3'],
  SphericalSegment: ['nodeId', 'treeIndex', 'color', 'center', 'normal', 'radius', 'height'],
  TorusSegment: ['nodeId', 'treeIndex', 'color', 'center', 'normal', 'radius', 'tubeRadius', 'angle', 'arcAngle'],
  Trapezium: ['nodeId', 'treeIndex', 'color', 'vertex1', 'vertex2', 'vertex3', 'vertex4'],
};

const renderedGeometryParameters: any = {
  Box: { hasCustomTransformProperties: false },
  Circle: { hasCustomTransformProperties: false },
  Cone: { hasCustomTransformProperties: true },
  EccentricCone: { hasCustomTransformProperties: true },
  EllipsoidSegment: { hasCustomTransformProperties: true },
  GeneralCylinder: { hasCustomTransformProperties: false },
  GeneralRing: { hasCustomTransformProperties: false },
  InstancedMesh: { },
  MergedMesh: { },
  Nut: { hasCustomTransformProperties: false },
  Quad: { hasCustomTransformProperties: true },
  SphericalSegment: { hasCustomTransformProperties: true },
  TorusSegment: { hasCustomTransformProperties: false },
  Trapezium: { hasCustomTransformProperties: true },
};
