export type RenderedPrimitiveNameType =
  | 'InstancedMesh'
  | 'MergedMesh'
  | 'Box'
  | 'Circle'
  | 'Cone'
  | 'EccentricCone'
  | 'EllipsoidSegment'
  | 'GeneralCylinder'
  | 'GeneralRing'
  | 'Nut'
  | 'Quad'
  | 'SphericalSegment'
  | 'TorusSegment'
  | 'Trapezium';
